error: used unimplemented, unreachable, todo or panic in a function that returns result
  --> $DIR/panic_in_result.rs:6:5
   |
LL | /     fn result_with_panic() -> Result<bool, String> // should emit lint
LL | |     {
LL | |         panic!("error");
LL | |     }
   | |_____^
   |
   = note: `-D clippy::panic-in-result` implied by `-D warnings`
   = help: unimplemented, unreachable, todo or panic should not be used in a function that returns result
note: will cause the application to crash.
  --> $DIR/panic_in_result.rs:8:9
   |
LL |         panic!("error");
   |         ^^^^^^^^^^^^^^^^
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: used unimplemented, unreachable, todo or panic in a function that returns result
  --> $DIR/panic_in_result.rs:11:5
   |
LL | /     fn result_with_unimplemented() -> Result<bool, String> // should emit lint
LL | |     {
LL | |         unimplemented!();
LL | |     }
   | |_____^
   |
   = help: unimplemented, unreachable, todo or panic should not be used in a function that returns result
note: will cause the application to crash.
  --> $DIR/panic_in_result.rs:13:9
   |
LL |         unimplemented!();
   |         ^^^^^^^^^^^^^^^^^
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: used unimplemented, unreachable, todo or panic in a function that returns result
  --> $DIR/panic_in_result.rs:16:5
   |
LL | /     fn result_with_unreachable() -> Result<bool, String> // should emit lint
LL | |     {
LL | |         unreachable!();
LL | |     }
   | |_____^
   |
   = help: unimplemented, unreachable, todo or panic should not be used in a function that returns result
note: will cause the application to crash.
  --> $DIR/panic_in_result.rs:18:9
   |
LL |         unreachable!();
   |         ^^^^^^^^^^^^^^^
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: used unimplemented, unreachable, todo or panic in a function that returns result
  --> $DIR/panic_in_result.rs:21:5
   |
LL | /     fn result_with_todo() -> Result<bool, String> // should emit lint
LL | |     {
LL | |         todo!("Finish this");
LL | |     }
   | |_____^
   |
   = help: unimplemented, unreachable, todo or panic should not be used in a function that returns result
note: will cause the application to crash.
  --> $DIR/panic_in_result.rs:23:9
   |
LL |         todo!("Finish this");
   |         ^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 4 previous errors

